### ISSUE TITLE
Error Connection Refused

### ISSUE THREAD

**Issue by g4laura** [malithmcr/react-php-contact-form#12]
When I click submit on the form I get this error:
http://localhost/react-contact-form/api/contact/index.php net::ERR_CONNECTION_REFUSED

I'm not sure what I'm doing wrong

**Comment by malithmcr** [comment]
One thing is for sure, this is a backend problem. This happens when the cross origin communication between the backend and frontend is not connected properly. 

Please try to access this link directly on the browser: 

http://localhost/react-contact-form/api/contact/index.php

and let me know if you get any errors? 

:) :)

**Comment by r-wells** [comment]
I'm getting this same issue and going to that page returns an object not found

**Comment by malithmcr** [comment]
@r-wells did you run docker-compose up -d on the root?  could you try to open http://localhost/react-contact-form/api/contact/index.php on your browser and share a screenshot?
